apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
# Red Hat OpenShift AI installs in AllNamespaces mode, so this OperatorGroup has
# an empty spec (no targetNamespaces).
spec: {}
